# Generated by Django 5.2 on 2025-06-12 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Task Name"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("u", "Not started yet"),
                            ("o", "Ongoing"),
                            ("f", "Finished"),
                        ],
                        max_length=1,
                        verbose_name="Task Status",
                    ),
                ),
            ],
        ),
    ]
